apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aqua-ingress
spec:
  ingressClassName: nginx # <--- ESTO ES VITAL
  rules:
  - host: aqua.k8slab.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aqua-svc
            port:
              number: 80