apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maroon-ingress
  # namespace: trouble-3
spec:
  ingressClassName: nginx # <--- ESTO ES VITAL
  rules:
  - host: maroon.k8slab.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: maroon-svc
            port:
              number: 80