apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: olive-ingress
spec:
  ingressClassName: nginx # <--- ESTO ES VITAL
  rules:
  - host: olive.k8slab.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: olive-svc
            port:
              number: 80