apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lights-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: lights.k8slab.net
      http:
        paths:
          # 1. Primero las rutas específicas
          - path: /red
            pathType: Prefix
            backend:
              service:
                name: red-svc
                port:
                  number: 8080

          - path: /green
            pathType: Prefix
            backend:
              service:
                name: green-svc
                port:
                  number: 8080

          - path: /yellow
            pathType: Prefix
            backend:
              service:
                name: yellow-svc
                port:
                  number: 8080

          # 2. La ruta raíz SIEMPRE al final
          - path: /
            pathType: Prefix
            backend:
              service:
                name: switch
                port:
                  number: 80